### ISSUE TITLE
Deprecate Viper 

### ISSUE THREAD

**Issue by jdknives** [skycoin/cx-chains#22]
Viper is only imported by 

`./src/fiber/config.go`

It is quite heavy in terms of dependencies so it may be wise to replace it with some other tool such as:

https://github.com/jmartin82/mconfig or another tool that is lighter. Alternatively, maybe one can get around using a separate tool at all.

**Comment by evanlinjin** [comment]
Removed in #25

**Comment by SkycoinSynth** [comment]
git checkout 1437cd272658b56c51cc1c0fac99b7ff0d536647

~/go/src/github.com/skycoin/cx-chains$ grep -rn "viper" ./src/.
./src/./fiber/config.go:10:	"github.com/spf13/viper"
./src/./fiber/config.go:103:	// set viper parameters
./src/./fiber/config.go:109:		viper.SetConfigType(confNameSplit[len(confNameSplit)-1])
./src/./fiber/config.go:115:	viper.SetConfigName(configName)
./src/./fiber/config.go:118:		viper.AddConfigPath(appDir)
./src/./fiber/config.go:120:	viper.AddConfigPath(".")
./src/./fiber/config.go:127:	if err := viper.ReadInConfig(); err != nil {
./src/./fiber/config.go:131:	if err := viper.Unmarshal(&params); err != nil {
./src/./fiber/config.go:140:	viper.SetDefault("node.genesis_coin_volume", 100e12)
./src/./fiber/config.go:141:	viper.SetDefault("node.port", 6000)
./src/./fiber/config.go:142:	viper.SetDefault("node.web_interface_port", 6420)
./src/./fiber/config.go:143:	viper.SetDefault("node.unconfirmed_burn_factor", 10)
./src/./fiber/config.go:144:	viper.SetDefault("node.unconfirmed_max_transaction_size", 5*1024*1024)
./src/./fiber/config.go:145:	viper.SetDefault("node.unconfirmed_max_decimals", 3)
./src/./fiber/config.go:146:	viper.SetDefault("node.create_block_burn_factor", 10)
./src/./fiber/config.go:147:	viper.SetDefault("node.create_block_max_transaction_size", 5*1024*1024)
./src/./fiber/config.go:148:	viper.SetDefault("node.create_block_max_decimals", 3)
./src/./fiber/config.go:149:	viper.SetDefault("node.max_block_transactions_size", 5*1024*1024)
./src/./fiber/config.go:150:	viper.SetDefault("node.display_name", "Skycoin")
./src/./fiber/config.go:151:	viper.SetDefault("node.ticker", "SKY")
./src/./fiber/config.go:152:	viper.SetDefault("node.coin_hours_display_name", "Coin Hours")
./src/./fiber/config.go:153:	viper.SetDefault("node.coin_hours_ticker", "SCH")
./src/./fiber/config.go:154:	viper.SetDefault("node.explorer_url", "https://explorer.skycoin.net")
./src/./fiber/config.go:157:	viper.SetDefault("build.commit", "")
./src/./fiber/config.go:158:	viper.SetDefault("build.branch", "")
./src/./fiber/config.go:161:	viper.SetDefault("params.max_coin_supply", 1e8)
./src/./fiber/config.go:162:	viper.SetDefault("params.initial_unlocked_count", 25)
./src/./fiber/config.go:163:	viper.SetDefault("params.unlock_address_rate", 5)
./src/./fiber/config.go:164:	viper.SetDefault("params.unlock_time_interval", 60*60*24*365)
./src/./fiber/config.go:165:	viper.SetDefault("params.user_max_decimals", 3)
./src/./fiber/config.go:166:	viper.SetDefault("params.user_burn_factor", 10)
./src/./fiber/config.go:167:	viper.SetDefault("params.user_max_transaction_size", 128*1024*1024)

**Comment by SkycoinSynth** [comment]
> Removed in #25

There is only one commit in #25.

There is no commit in #25 with a description that states that viper was removed.

Multiple separate commits in #25 are placed inside a single commit, making the pull request unreadable and unreviewable.

There should be as single, individial commit for each removal or each ticket and each task.

No commit in #25 states that viper was removed.
