### ISSUE TITLE
In Templates, delete everything related to wallets

### ISSUE THREAD

**Issue by SkycoinSynth** [skycoin/cx-chains#7]
Delete everything in the interface related to wallets.
- leave networking and connection tab

Front page should be diagnostics
- genesis hash, time since last block, number of blocks, etc

**Comment by jdknives** [comment]
Fixed partially by #17 . Got rid of the UI. Creating the new GUI should be done with something more lightweight like Fyne for instance if it is not exposed to average customers.

**Comment by evanlinjin** [comment]
@SkycoinSynth Can you please elaborate on this?

**Comment by evanlinjin** [comment]
GUI is already removed.
